# Generated by Django 4.0.4 on 2022-07-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
