# Generated by Django 3.2.5 on 2022-05-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_usertwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTwo',
        ),
    ]
