# Generated by Django 4.0.4 on 2022-05-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('car', models.CharField(max_length=200)),
                ('beer', models.CharField(max_length=200)),
            ],
        ),
    ]
