# Generated by Django 4.0.4 on 2022-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_questionsform_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsform',
            name='owner',
            field=models.CharField(max_length=200),
        ),
    ]
