# Generated by Django 4.0.4 on 2022-07-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_questionsform_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
